//! Config file handling, mirroring dory: `~/.dory.yml` → `~/.aka.toml`,
//! project-local `.aka.toml` searched from cwd upwards, defaults for anything
//! the user did not set. TOML root = the `aka` table (dory's `dory:` root,
//! minus the wrapper); sections `[dns]`, `[proxy]`, `[resolv]` map to dory's
//! `dnsmasq`, `nginx_proxy` and `resolv`.

use std::collections::BTreeSet;
use std::path::{Path, PathBuf};

use aka_kernel::BoxedError;
use aka_kernel::config::AkaConfig;
use toml::Value;

use crate::paths::default_config_path;

pub const CONFIG_FILENAME: &str = ".aka.toml";
pub const FILE_MARKER: &str = "# aka config file";

/// Commented default config, generated by `aka config-file` (dory parity).
pub const DEFAULT_TOML: &str = r##"# aka config file
#
# Be careful changing these; dns, proxy and the host resolver must agree.
# For example, resolv expects a nameserver listening at resolv.nameserver:port,
# and dns publishes its port on dns.bind_ip.

[dns]
enabled = true
image = "dewey4iv/aka-dns:latest"    # aka pull, or build with bin/build.sh
container_name = "aka_dns"
port = 53                    # must be 53 unless resolv.port matches this
bind_ip = "127.0.0.1"        # host interface the dns ports are published on
# kill_others: what to do when a process already holds the dns port:
#   ask (prompt per process), yes/true (kill without asking), no/false (fail)
kill_others = "ask"

# Every domain (and all of its subdomains) resolves to its address.
# Add as many as you like: dory only served its `tld`; aka can serve
# docker, test, localhost, dev, ... side by side.
[[dns.domains]]
domain = "docker"            # use '#' for a catch-all wildcard
address = "127.0.0.1"        # answer returned for queries against the domain
# [[dns.domains]]
# domain = "test"
# address = "127.0.0.1"
# [[dns.domains]]
# domain = "localhost"       # needs an explicit entry like this one for
# address = "127.0.0.1"      # dnsmasq to answer *.localhost (CLI tools)

[proxy]
enabled = true
image = "dewey4iv/aka-proxy:latest"  # angie-based proxy, devops/docker/aka-proxy
container_name = "aka_proxy"
network = "aka"              # docker network the proxy lives on
http_port = 80               # host port published for http vhosts
tls_enabled = true           # publish tls_port and enable SNI routing
tls_port = 443
ssl_certs_dir = ""           # host dir with <host>.crt/.key pairs to terminate TLS
bind_ip = "127.0.0.1"
restart = "unless-stopped"

[resolv]
enabled = true               # write /etc/resolver/<domain> files (macOS) or resolv.conf (linux)
nameserver = "127.0.0.1"     # nameserver written; match dns.bind_ip
# port = 53                  # defaults to dns.port when unset
"##;

/// Find the config file: explicit path, else `.aka.toml` from `start_dir` up
/// to `/`, else the default location. Returns `None` when nothing exists
/// (defaults apply).
pub fn find_config_file(start_dir: &Path, explicit: Option<&Path>) -> Option<PathBuf> {
    if let Some(path) = explicit {
        return Some(path.to_path_buf());
    }

    let mut dir = start_dir.to_path_buf();
    loop {
        let candidate = dir.join(CONFIG_FILENAME);
        if candidate.is_file() {
            return Some(candidate);
        }
        if !dir.pop() {
            break;
        }
    }

    let default = default_config_path();
    default.is_file().then_some(default)
}

pub fn load_config(path: &Path) -> Result<AkaConfig, BoxedError> {
    let raw = std::fs::read_to_string(path)?;
    parse_config(&raw)
}

/// Load the config for `start_dir`, falling back to defaults.
pub fn load_or_default(start_dir: &Path, explicit: Option<&Path>) -> Result<AkaConfig, BoxedError> {
    match find_config_file(start_dir, explicit) {
        Some(path) if path.is_file() => load_config(&path),
        _ => parse_config(DEFAULT_TOML),
    }
}

fn parse_config(raw: &str) -> Result<AkaConfig, BoxedError> {
    let defaults: Value = raw_toml(DEFAULT_TOML)?;
    let user: Value = raw_toml(raw)?;
    let merged = deep_merge(defaults, user);
    Ok(normalize(merged.try_into()?))
}

fn raw_toml(raw: &str) -> Result<Value, BoxedError> {
    toml::from_str(raw).map_err(Into::into)
}

/// Fill cross-section defaults (resolv.port <- dns.port).
fn normalize(mut cfg: AkaConfig) -> AkaConfig {
    if cfg.resolv.port.is_none() {
        cfg.resolv.port = Some(cfg.dns.port);
    }
    cfg
}

fn deep_merge(base: Value, other: Value) -> Value {
    match (base, other) {
        (Value::Table(mut base), Value::Table(other)) => {
            for (key, value) in other {
                let merged = match base.remove(&key) {
                    Some(existing) => deep_merge(existing, value),
                    None => value,
                };
                base.insert(key, merged);
            }
            Value::Table(base)
        }
        // arrays replace wholesale (dns.domains lists are complete statements)
        (_, other) => other,
    }
}

/// Write the commented default config. Refuses to overwrite unless `force`.
pub fn write_default_config(path: &Path, force: bool) -> Result<(), BoxedError> {
    if path.exists() && !force {
        return Err(format!(
            "{} exists; pass --force to overwrite or --upgrade to merge new keys in",
            path.display()
        )
        .into());
    }
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(path, DEFAULT_TOML)?;
    Ok(())
}

/// Rewrite an existing config with defaults merged in (user values win),
/// so newly introduced keys appear. Comments in the old file are dropped.
pub fn upgrade_config_file(path: &Path) -> Result<(), BoxedError> {
    let raw = std::fs::read_to_string(path)?;
    let user: Value = raw_toml(&raw)?;
    let defaults: Value = raw_toml(DEFAULT_TOML)?;
    let merged = deep_merge(defaults, user);
    let doc = format!(
        "{FILE_MARKER} (upgraded; comments regenerated by `aka config-file --upgrade`)\n{}",
        toml::to_string_pretty(&merged)?
    );
    std::fs::write(path, doc)?;
    Ok(())
}

/// The domains aka serves DNS + resolver entries for.
pub fn domains(cfg: &AkaConfig) -> BTreeSet<String> {
    cfg.dns.domains.iter().map(|d| d.domain.clone()).collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn defaults_parse() {
        let cfg = parse_config(DEFAULT_TOML).expect("defaults must parse");
        assert_eq!(cfg.dns.container_name, "aka_dns");
        assert_eq!(cfg.proxy.container_name, "aka_proxy");
        assert_eq!(cfg.dns.domains.len(), 1, "commented extras stay out");
        assert_eq!(cfg.dns.domains[0].domain, "docker");
        assert_eq!(cfg.resolv.port, Some(53));
        assert_eq!(cfg.dns.kill_others.answer(), None);
    }

    #[test]
    fn user_values_override_defaults_deeply() {
        let cfg = parse_config(
            r#"
[dns]
port = 19323
[[dns.domains]]
domain = "localhost"
address = "127.0.0.1"
[[dns.domains]]
domain = "test"
address = "127.0.0.1"

[proxy]
tls_enabled = false
"#,
        )
        .unwrap();

        assert_eq!(cfg.dns.port, 19323);
        assert_eq!(cfg.resolv.port, Some(19323));
        assert_eq!(cfg.dns.domains.len(), 2);
        assert_eq!(cfg.dns.domains[1].domain, "test");
        assert!(!cfg.proxy.tls_enabled);
        // untouched nested values keep their defaults
        assert_eq!(cfg.dns.container_name, "aka_dns");
        assert_eq!(cfg.proxy.http_port, 80);
    }

    #[test]
    fn kill_others_answers() {
        let cfg = parse_config("[dns]\nkill_others = \"yes\"\n").unwrap();
        assert_eq!(cfg.dns.kill_others.answer(), Some(true));
        let cfg = parse_config("[dns]\nkill_others = false\n").unwrap();
        assert_eq!(cfg.dns.kill_others.answer(), Some(false));
    }

    #[test]
    fn unknown_keys_are_rejected() {
        let err = parse_config("typo_key = 1\n").unwrap_err();
        assert!(err.to_string().contains("typo_key"), "{err}");
        let err = parse_config("[dns]\ntypo_key = 1\n").unwrap_err();
        assert!(err.to_string().contains("typo_key"), "{err}");
    }

    #[test]
    fn upgrade_adds_missing_keys_and_keeps_user_values() {
        let dir = std::env::temp_dir().join(format!("aka-cfg-up-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join(CONFIG_FILENAME);
        std::fs::write(&path, "[dns]\nport = 5353\n").unwrap();

        upgrade_config_file(&path).unwrap();
        let cfg = load_config(&path).unwrap();

        assert_eq!(cfg.dns.port, 5353, "user value survives");
        assert_eq!(cfg.proxy.container_name, "aka_proxy", "new keys merged in");
        assert_eq!(cfg.dns.domains[0].domain, "docker", "defaults restored");

        std::fs::remove_dir_all(&dir).unwrap();
    }
}
