//! Config file handling, mirroring dory: `~/.dory.yml` → `~/.aka.yml`,
//! project-local `.aka.yml` searched from cwd upwards, defaults for anything
//! the user did not set.

use std::collections::BTreeSet;
use std::path::{Path, PathBuf};

use aka_kernel::BoxedError;
use aka_kernel::config::AkaConfig;
use serde_yaml::Value;

use crate::paths::default_config_path;

pub const CONFIG_FILENAME: &str = ".aka.yml";
pub const FILE_MARKER: &str = "# aka config file";

/// Commented default config, generated by `aka config-file` (dory parity).
pub const DEFAULT_YAML: &str = r#"# aka config file
aka:
  # Be careful changing these; dns, proxy and the host resolver must agree.
  dns:
    enabled: true
    domains:                 # domains resolved (with all subdomains) to an address
      - domain: docker       # use '#' for a catch-all wildcard
        address: 127.0.0.1   # answer returned for queries against the domain
    container_name: aka_dns
    image: aka-dns:local     # build with bin/build.sh (bin/push.sh for a registry tag)
    port: 53                 # must be 53 unless resolv.port matches this
    bind_ip: 127.0.0.1       # host interface the dns ports are published on
    # kill_others: what to do when a process already holds the dns port:
    #   ask (prompt per process), yes/true (kill without asking), no/false (fail)
    kill_others: ask
  proxy:
    enabled: true
    container_name: aka_proxy
    image: aka-proxy:local   # angie-based proxy, built from src/aka/build/proxy
    network: aka             # docker network the proxy lives on
    http_port: 80            # host port published for http vhosts
    tls_enabled: true        # publish tls_port and enable SNI routing
    tls_port: 443
    ssl_certs_dir: ''        # host dir with <host>.crt/.key pairs to terminate TLS
    bind_ip: 127.0.0.1
    restart: unless-stopped
  resolv:
    enabled: true            # write /etc/resolver/<domain> files (macOS) or resolv.conf (linux)
    nameserver: 127.0.0.1    # nameserver written; match dns.bind_ip
    port:                    # defaults to dns.port when empty
"#;

/// Find the config file: explicit path, else `.aka.yml` from `start_dir` up
/// to `/`, else the default location. Returns `None` when nothing exists
/// (defaults apply).
pub fn find_config_file(start_dir: &Path, explicit: Option<&Path>) -> Option<PathBuf> {
    if let Some(path) = explicit {
        return Some(path.to_path_buf());
    }

    let mut dir = start_dir.to_path_buf();
    loop {
        let candidate = dir.join(CONFIG_FILENAME);
        if candidate.is_file() {
            return Some(candidate);
        }
        if !dir.pop() {
            break;
        }
    }

    let default = default_config_path();
    default.is_file().then_some(default)
}

pub fn load_config(path: &Path) -> Result<AkaConfig, BoxedError> {
    let raw = std::fs::read_to_string(path)?;
    parse_config(&raw)
}

/// Load the config for `start_dir`, falling back to defaults.
pub fn load_or_default(start_dir: &Path, explicit: Option<&Path>) -> Result<AkaConfig, BoxedError> {
    match find_config_file(start_dir, explicit) {
        Some(path) if path.is_file() => load_config(&path),
        _ => parse_config(DEFAULT_YAML),
    }
}

fn parse_config(raw: &str) -> Result<AkaConfig, BoxedError> {
    let defaults: Value = serde_yaml::from_str(DEFAULT_YAML)?;
    let user: Value = serde_yaml::from_str(raw)?;
    let merged = deep_merge(defaults, user);
    let file: aka_kernel::config::AkaFile = serde_yaml::from_value(merged)?;
    Ok(normalize(file.aka))
}

/// Fill cross-section defaults (resolv.port <- dns.port).
fn normalize(mut cfg: AkaConfig) -> AkaConfig {
    if cfg.resolv.port.is_none() {
        cfg.resolv.port = Some(cfg.dns.port);
    }
    cfg
}

fn deep_merge(base: Value, other: Value) -> Value {
    match (base, other) {
        (Value::Mapping(mut base), Value::Mapping(other)) => {
            for (key, value) in other {
                let merged = match base.remove(&key) {
                    Some(existing) => deep_merge(existing, value),
                    None => value,
                };
                base.insert(key, merged);
            }
            Value::Mapping(base)
        }
        (_, other) => other,
    }
}

/// Write the commented default config. Refuses to overwrite unless `force`.
pub fn write_default_config(path: &Path, force: bool) -> Result<(), BoxedError> {
    if path.exists() && !force {
        return Err(format!(
            "{} exists; pass --force to overwrite or --upgrade to merge new keys in",
            path.display()
        )
        .into());
    }
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(path, DEFAULT_YAML)?;
    Ok(())
}

/// Rewrite an existing config with defaults merged in (user values win),
/// so newly introduced keys appear. Comments in the old file are dropped.
pub fn upgrade_config_file(path: &Path) -> Result<(), BoxedError> {
    let raw = std::fs::read_to_string(path)?;
    let user: Value = serde_yaml::from_str(&raw)?;
    let defaults: Value = serde_yaml::from_str(DEFAULT_YAML)?;
    let merged = deep_merge(defaults, user);
    let doc = format!("{FILE_MARKER}\n{}", serde_yaml::to_string(&merged)?);
    std::fs::write(path, doc)?;
    Ok(())
}

/// The domains aka serves DNS + resolver entries for.
pub fn domains(cfg: &AkaConfig) -> BTreeSet<String> {
    cfg.dns.domains.iter().map(|d| d.domain.clone()).collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn defaults_parse() {
        let cfg = parse_config(DEFAULT_YAML).expect("defaults must parse");
        assert_eq!(cfg.dns.container_name, "aka_dns");
        assert_eq!(cfg.proxy.container_name, "aka_proxy");
        assert_eq!(cfg.dns.domains[0].domain, "docker");
        assert_eq!(cfg.resolv.port, Some(53));
        assert_eq!(cfg.dns.kill_others.answer(), None);
    }

    #[test]
    fn user_values_override_defaults_deeply() {
        let cfg = parse_config(
            r#"
aka:
  dns:
    port: 19323
    domains:
      - domain: localhost
        address: 127.0.0.1
      - domain: test
        address: 127.0.0.1
  proxy:
    tls_enabled: false
"#,
        )
        .unwrap();

        assert_eq!(cfg.dns.port, 19323);
        assert_eq!(cfg.resolv.port, Some(19323));
        assert_eq!(cfg.dns.domains.len(), 2);
        assert_eq!(cfg.dns.domains[1].domain, "test");
        assert!(!cfg.proxy.tls_enabled);
        // untouched nested values keep their defaults
        assert_eq!(cfg.dns.container_name, "aka_dns");
        assert_eq!(cfg.proxy.http_port, 80);
    }

    #[test]
    fn kill_others_answers() {
        let cfg = parse_config("aka:\n  dns:\n    kill_others: yes\n").unwrap();
        assert_eq!(cfg.dns.kill_others.answer(), Some(true));
        let cfg = parse_config("aka:\n  dns:\n    kill_others: false\n").unwrap();
        assert_eq!(cfg.dns.kill_others.answer(), Some(false));
    }

    #[test]
    fn unknown_keys_are_rejected() {
        let err = parse_config("aka:\n  typo_key: 1\n").unwrap_err();
        assert!(err.to_string().contains("typo_key"));
    }
}
